version: '3.9'
services:
  api-backend:
    image: knightkill/14kb-api:latest
    ports:
      - '8080:3000'
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
      update_config:
        parallelism: 1
        delay: 10s
      healthcheck:
        test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
        interval: 15s
        timeout: 5s
        retries: 5
    secrets:
      - api_env
  web-ui:
    image: knightkill/14kb-ui:latest
    ports:
      - '80:80'
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
  load-agent:
    image: grafana/k6:latest
    deploy:
      mode: global
      restart_policy:
        condition: none
secrets:
  api_env:
    file: backend/.env.example
